# Generated by Django 3.2 on 2023-04-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230404_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_est',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('pagado', 'Pagado'), ('entregado', 'Entregado')], default='solicitado', max_length=100, verbose_name='Estado'),
        ),
    ]
